apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  annotations:
    broker.platform-mesh.io/secret-name: kubeconfig-externalca
  name: v1alpha1.certificates.identity.generic.platform-mesh.io
spec:
  filters:
  - key: fqdn
    suffix: corp.com
  gvr:
    group: identity.generic.platform-mesh.io
    resource: certificates
    version: v1alpha1
