name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    uses: platform-mesh/.github/.github/workflows/job-golang-lint.yml@9ddacafbe3260312cb1cc3f9974ad2fece8effe0
    with:
      useTask: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Enable git CLI clones using GITHUB_TOKEN
        run: |
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install envtest binaries
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          echo "KUBEBUILDER_ASSETS=$($(go env GOPATH)/bin/setup-envtest use 1.29.0 -p path)" >> $GITHUB_ENV
      - name: Test
        run: task cover
      - name: Install Code Coverage
        run: go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Check Test Coverage with Config
        run: go-test-coverage --profile cover.out --config ./.testcoverage.yml

  docker-build:
    uses: platform-mesh/.github/.github/workflows/job-docker-build.yml@9ddacafbe3260312cb1cc3f9974ad2fece8effe0
    with:
      imageTagName: ghcr.io/platform-mesh/backup-operator

  quality-gate:
    if: always()
    permissions: {}
    needs: [lint, test, docker-build]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            echo "lint failed"
            exit 1
          fi
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "test failed"
            exit 1
          fi
          if [[ "${{ needs.docker-build.result }}" != "success" ]]; then
            echo "docker-build failed"
            exit 1
          fi
