// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	v1alpha1 "github.com/platform-mesh/account-operator/api/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// Retriever is an autogenerated mock type for the Retriever type
type Retriever struct {
	mock.Mock
}

type Retriever_Expecter struct {
	mock *mock.Mock
}

func (_m *Retriever) EXPECT() *Retriever_Expecter {
	return &Retriever_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, accountPath
func (_m *Retriever) Get(ctx context.Context, accountPath string) (*v1alpha1.AccountInfo, error) {
	ret := _m.Called(ctx, accountPath)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha1.AccountInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.AccountInfo, error)); ok {
		return rf(ctx, accountPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.AccountInfo); ok {
		r0 = rf(ctx, accountPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.AccountInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Retriever_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Retriever_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - accountPath string
func (_e *Retriever_Expecter) Get(ctx interface{}, accountPath interface{}) *Retriever_Get_Call {
	return &Retriever_Get_Call{Call: _e.mock.On("Get", ctx, accountPath)}
}

func (_c *Retriever_Get_Call) Run(run func(ctx context.Context, accountPath string)) *Retriever_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Retriever_Get_Call) Return(_a0 *v1alpha1.AccountInfo, _a1 error) *Retriever_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Retriever_Get_Call) RunAndReturn(run func(context.Context, string) (*v1alpha1.AccountInfo, error)) *Retriever_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetriever creates a new instance of Retriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *Retriever {
	mock := &Retriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
