/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	v1alpha10 "github.com/kcp-dev/sdk/apis/core/v1alpha1"
	"github.com/kcp-dev/sdk/client/applyconfiguration/core/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
)

// NewLogicalClusterInterface creates a new instance of LogicalClusterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogicalClusterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogicalClusterInterface {
	mock := &LogicalClusterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LogicalClusterInterface is an autogenerated mock type for the LogicalClusterInterface type
type LogicalClusterInterface struct {
	mock.Mock
}

type LogicalClusterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *LogicalClusterInterface) EXPECT() *LogicalClusterInterface_Expecter {
	return &LogicalClusterInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Apply(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, logicalCluster, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type LogicalClusterInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha1.LogicalClusterApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *LogicalClusterInterface_Expecter) Apply(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Apply_Call {
	return &LogicalClusterInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Apply_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions)) *LogicalClusterInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.LogicalClusterApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.LogicalClusterApplyConfiguration)
		}
		var arg2 v1.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v1.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Apply_Call) Return(result *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_Apply_Call) RunAndReturn(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) ApplyStatus(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, logicalCluster, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.LogicalClusterApplyConfiguration, v1.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type LogicalClusterInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha1.LogicalClusterApplyConfiguration
//   - opts v1.ApplyOptions
func (_e *LogicalClusterInterface_Expecter) ApplyStatus(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_ApplyStatus_Call {
	return &LogicalClusterInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions)) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.LogicalClusterApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.LogicalClusterApplyConfiguration)
		}
		var arg2 v1.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v1.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) Return(result *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_ApplyStatus_Call) RunAndReturn(run func(ctx context.Context, logicalCluster *v1alpha1.LogicalClusterApplyConfiguration, opts v1.ApplyOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Create(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.CreateOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.CreateOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, logicalCluster, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.CreateOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha10.LogicalCluster, v1.CreateOptions) error); ok {
		r1 = returnFunc(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LogicalClusterInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha10.LogicalCluster
//   - opts v1.CreateOptions
func (_e *LogicalClusterInterface_Expecter) Create(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Create_Call {
	return &LogicalClusterInterface_Create_Call{Call: _e.mock.On("Create", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Create_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.CreateOptions)) *LogicalClusterInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha10.LogicalCluster
		if args[1] != nil {
			arg1 = args[1].(*v1alpha10.LogicalCluster)
		}
		var arg2 v1.CreateOptions
		if args[2] != nil {
			arg2 = args[2].(v1.CreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Create_Call) Return(logicalCluster1 *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_Create_Call {
	_c.Call.Return(logicalCluster1, err)
	return _c
}

func (_c *LogicalClusterInterface_Create_Call) RunAndReturn(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.CreateOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LogicalClusterInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LogicalClusterInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *LogicalClusterInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *LogicalClusterInterface_Delete_Call {
	return &LogicalClusterInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *LogicalClusterInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *LogicalClusterInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1.DeleteOptions
		if args[2] != nil {
			arg2 = args[2].(v1.DeleteOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Delete_Call) Return(err error) *LogicalClusterInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LogicalClusterInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, opts v1.DeleteOptions) error) *LogicalClusterInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	ret := _mock.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.DeleteOptions, v1.ListOptions) error); ok {
		r0 = returnFunc(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LogicalClusterInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type LogicalClusterInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.DeleteOptions
//   - listOpts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *LogicalClusterInterface_DeleteCollection_Call {
	return &LogicalClusterInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions)) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.DeleteOptions
		if args[1] != nil {
			arg1 = args[1].(v1.DeleteOptions)
		}
		var arg2 v1.ListOptions
		if args[2] != nil {
			arg2 = args[2].(v1.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) Return(err error) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LogicalClusterInterface_DeleteCollection_Call) RunAndReturn(run func(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error) *LogicalClusterInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = returnFunc(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LogicalClusterInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *LogicalClusterInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *LogicalClusterInterface_Get_Call {
	return &LogicalClusterInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *LogicalClusterInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *LogicalClusterInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1.GetOptions
		if args[2] != nil {
			arg2 = args[2].(v1.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Get_Call) Return(logicalCluster *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_Get_Call {
	_c.Call.Return(logicalCluster, err)
	return _c
}

func (_c *LogicalClusterInterface_Get_Call) RunAndReturn(run func(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*v1alpha10.LogicalClusterList, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1alpha10.LogicalClusterList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*v1alpha10.LogicalClusterList, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v1alpha10.LogicalClusterList); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalClusterList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type LogicalClusterInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) List(ctx interface{}, opts interface{}) *LogicalClusterInterface_List_Call {
	return &LogicalClusterInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *LogicalClusterInterface_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *LogicalClusterInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v1.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_List_Call) Return(logicalClusterList *v1alpha10.LogicalClusterList, err error) *LogicalClusterInterface_List_Call {
	_c.Call.Return(logicalClusterList, err)
	return _c
}

func (_c *LogicalClusterInterface_List_Call) RunAndReturn(run func(ctx context.Context, opts v1.ListOptions) (*v1alpha10.LogicalClusterList, error)) *LogicalClusterInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*v1alpha10.LogicalCluster, error) {
	var tmpRet mock.Arguments
	if len(subresources) > 0 {
		tmpRet = _mock.Called(ctx, name, pt, data, opts, subresources)
	} else {
		tmpRet = _mock.Called(ctx, name, pt, data, opts)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, name, pt, data, opts, subresources...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v1.PatchOptions, ...string) error); ok {
		r1 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type LogicalClusterInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v1.PatchOptions
//   - subresources ...string
func (_e *LogicalClusterInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *LogicalClusterInterface_Patch_Call {
	return &LogicalClusterInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *LogicalClusterInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string)) *LogicalClusterInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.PatchType
		if args[2] != nil {
			arg2 = args[2].(types.PatchType)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 v1.PatchOptions
		if args[4] != nil {
			arg4 = args[4].(v1.PatchOptions)
		}
		var arg5 []string
		var variadicArgs []string
		if len(args) > 5 {
			variadicArgs = args[5].([]string)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Patch_Call) Return(result *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *LogicalClusterInterface_Patch_Call) RunAndReturn(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Update(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, logicalCluster, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LogicalClusterInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha10.LogicalCluster
//   - opts v1.UpdateOptions
func (_e *LogicalClusterInterface_Expecter) Update(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_Update_Call {
	return &LogicalClusterInterface_Update_Call{Call: _e.mock.On("Update", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_Update_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions)) *LogicalClusterInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha10.LogicalCluster
		if args[1] != nil {
			arg1 = args[1].(*v1alpha10.LogicalCluster)
		}
		var arg2 v1.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v1.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Update_Call) Return(logicalCluster1 *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_Update_Call {
	_c.Call.Return(logicalCluster1, err)
	return _c
}

func (_c *LogicalClusterInterface_Update_Call) RunAndReturn(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) UpdateStatus(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions) (*v1alpha10.LogicalCluster, error) {
	ret := _mock.Called(ctx, logicalCluster, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v1alpha10.LogicalCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) (*v1alpha10.LogicalCluster, error)); ok {
		return returnFunc(ctx, logicalCluster, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) *v1alpha10.LogicalCluster); ok {
		r0 = returnFunc(ctx, logicalCluster, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha10.LogicalCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha10.LogicalCluster, v1.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, logicalCluster, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type LogicalClusterInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logicalCluster *v1alpha10.LogicalCluster
//   - opts v1.UpdateOptions
func (_e *LogicalClusterInterface_Expecter) UpdateStatus(ctx interface{}, logicalCluster interface{}, opts interface{}) *LogicalClusterInterface_UpdateStatus_Call {
	return &LogicalClusterInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, logicalCluster, opts)}
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) Run(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions)) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha10.LogicalCluster
		if args[1] != nil {
			arg1 = args[1].(*v1alpha10.LogicalCluster)
		}
		var arg2 v1.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v1.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) Return(logicalCluster1 *v1alpha10.LogicalCluster, err error) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Return(logicalCluster1, err)
	return _c
}

func (_c *LogicalClusterInterface_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, logicalCluster *v1alpha10.LogicalCluster, opts v1.UpdateOptions) (*v1alpha10.LogicalCluster, error)) *LogicalClusterInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type LogicalClusterInterface
func (_mock *LogicalClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LogicalClusterInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type LogicalClusterInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *LogicalClusterInterface_Expecter) Watch(ctx interface{}, opts interface{}) *LogicalClusterInterface_Watch_Call {
	return &LogicalClusterInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *LogicalClusterInterface_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *LogicalClusterInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v1.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LogicalClusterInterface_Watch_Call) Return(interfaceParam watch.Interface, err error) *LogicalClusterInterface_Watch_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *LogicalClusterInterface_Watch_Call) RunAndReturn(run func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)) *LogicalClusterInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}
