apiVersion: broker.platform-mesh.io/v1alpha1
kind: AcceptAPI
metadata:
  annotations:
    broker.platform-mesh.io/kcp-apiexport-name: certificates
    broker.platform-mesh.io/secret-name: kubeconfig-cert-manager
  name: v1alpha1.certificates.identity.generic.platform-mesh.io
spec:
  gvr:
    group: identity.generic.platform-mesh.io
    version: v1alpha1
    resource: certificates
