apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- ../../broker/rbac
- deployment.yaml

images:
- name: operator
  newName: resource-broker-operator
  newTag: platform-mesh
