# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This configuration represents the bare minimum formatting and import-ordering
# rules. Each component have also have its own, stricter config.
#

version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - intrange
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    importas:
      alias:
        - pkg: go.platform-mesh.io/apis/(\w+)/(v[\w\d]+)
          alias: pm$1$2
        - pkg: go.platform-mesh.io/apis/(\w+)
          alias: pm$1
        - pkg: github.com/kcp-dev/sdk/apis/(\w+)/(v[\w\d]+)
          alias: kcp$1$2
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: ctrlruntimeclient
      no-unaliased: true
    revive:
      rules:
        - name: var-naming
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: blank-imports
          disabled: true
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  # defaults to 3, which often needlessly hides issues and forces
  # to re-run the linter across the entire repo many times
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(go.platform-mesh.io)
        - prefix(k8s.io,sigs.k8s.io)
        - prefix(github.com/kcp-dev)
        - blank
        - dot
      custom-order: true
      skip-generated: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
  exclusions:
    generated: lax
    paths:
      - "zz_generated.*\\.go$"
      - ".*conversion.*\\.go$"
      - third_party$
      - builtin$
      - examples$
