// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hashicorp/go-multierror"
	mock "github.com/stretchr/testify/mock"
)

// NewExtensionConfiguration creates a new instance of ExtensionConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExtensionConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExtensionConfiguration {
	mock := &ExtensionConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExtensionConfiguration is an autogenerated mock type for the ExtensionConfiguration type
type ExtensionConfiguration struct {
	mock.Mock
}

type ExtensionConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *ExtensionConfiguration) EXPECT() *ExtensionConfiguration_Expecter {
	return &ExtensionConfiguration_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ExtensionConfiguration
func (_mock *ExtensionConfiguration) Validate(bytes []byte, s string) (string, *multierror.Error) {
	ret := _mock.Called(bytes, s)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 *multierror.Error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) (string, *multierror.Error)); ok {
		return returnFunc(bytes, s)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) string); ok {
		r0 = returnFunc(bytes, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) *multierror.Error); ok {
		r1 = returnFunc(bytes, s)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*multierror.Error)
		}
	}
	return r0, r1
}

// ExtensionConfiguration_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ExtensionConfiguration_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - bytes []byte
//   - s string
func (_e *ExtensionConfiguration_Expecter) Validate(bytes interface{}, s interface{}) *ExtensionConfiguration_Validate_Call {
	return &ExtensionConfiguration_Validate_Call{Call: _e.mock.On("Validate", bytes, s)}
}

func (_c *ExtensionConfiguration_Validate_Call) Run(run func(bytes []byte, s string)) *ExtensionConfiguration_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExtensionConfiguration_Validate_Call) Return(s1 string, error *multierror.Error) *ExtensionConfiguration_Validate_Call {
	_c.Call.Return(s1, error)
	return _c
}

func (_c *ExtensionConfiguration_Validate_Call) RunAndReturn(run func(bytes []byte, s string) (string, *multierror.Error)) *ExtensionConfiguration_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// WithSchema provides a mock function for the type ExtensionConfiguration
func (_mock *ExtensionConfiguration) WithSchema(bytes []byte) error {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for WithSchema")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ExtensionConfiguration_WithSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithSchema'
type ExtensionConfiguration_WithSchema_Call struct {
	*mock.Call
}

// WithSchema is a helper method to define mock.On call
//   - bytes []byte
func (_e *ExtensionConfiguration_Expecter) WithSchema(bytes interface{}) *ExtensionConfiguration_WithSchema_Call {
	return &ExtensionConfiguration_WithSchema_Call{Call: _e.mock.On("WithSchema", bytes)}
}

func (_c *ExtensionConfiguration_WithSchema_Call) Run(run func(bytes []byte)) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExtensionConfiguration_WithSchema_Call) Return(err error) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ExtensionConfiguration_WithSchema_Call) RunAndReturn(run func(bytes []byte) error) *ExtensionConfiguration_WithSchema_Call {
	_c.Call.Return(run)
	return _c
}
