// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	openfgav1 "github.com/openfga/api/proto/openfga/v1"
	mock "github.com/stretchr/testify/mock"
)

// FGAStoreHelper is an autogenerated mock type for the FGAStoreHelper type
type FGAStoreHelper struct {
	mock.Mock
}

type FGAStoreHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *FGAStoreHelper) EXPECT() *FGAStoreHelper_Expecter {
	return &FGAStoreHelper_Expecter{mock: &_m.Mock}
}

// GetModelIDForTenant provides a mock function with given fields: ctx, conn, tenantID
func (_m *FGAStoreHelper) GetModelIDForTenant(ctx context.Context, conn openfgav1.OpenFGAServiceClient, tenantID string) (string, error) {
	ret := _m.Called(ctx, conn, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetModelIDForTenant")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, openfgav1.OpenFGAServiceClient, string) (string, error)); ok {
		return rf(ctx, conn, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, openfgav1.OpenFGAServiceClient, string) string); ok {
		r0 = rf(ctx, conn, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, openfgav1.OpenFGAServiceClient, string) error); ok {
		r1 = rf(ctx, conn, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FGAStoreHelper_GetModelIDForTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModelIDForTenant'
type FGAStoreHelper_GetModelIDForTenant_Call struct {
	*mock.Call
}

// GetModelIDForTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - conn openfgav1.OpenFGAServiceClient
//   - tenantID string
func (_e *FGAStoreHelper_Expecter) GetModelIDForTenant(ctx interface{}, conn interface{}, tenantID interface{}) *FGAStoreHelper_GetModelIDForTenant_Call {
	return &FGAStoreHelper_GetModelIDForTenant_Call{Call: _e.mock.On("GetModelIDForTenant", ctx, conn, tenantID)}
}

func (_c *FGAStoreHelper_GetModelIDForTenant_Call) Run(run func(ctx context.Context, conn openfgav1.OpenFGAServiceClient, tenantID string)) *FGAStoreHelper_GetModelIDForTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(openfgav1.OpenFGAServiceClient), args[2].(string))
	})
	return _c
}

func (_c *FGAStoreHelper_GetModelIDForTenant_Call) Return(_a0 string, _a1 error) *FGAStoreHelper_GetModelIDForTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FGAStoreHelper_GetModelIDForTenant_Call) RunAndReturn(run func(context.Context, openfgav1.OpenFGAServiceClient, string) (string, error)) *FGAStoreHelper_GetModelIDForTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetStoreIDForTenant provides a mock function with given fields: ctx, conn, tenantID
func (_m *FGAStoreHelper) GetStoreIDForTenant(ctx context.Context, conn openfgav1.OpenFGAServiceClient, tenantID string) (string, error) {
	ret := _m.Called(ctx, conn, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetStoreIDForTenant")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, openfgav1.OpenFGAServiceClient, string) (string, error)); ok {
		return rf(ctx, conn, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, openfgav1.OpenFGAServiceClient, string) string); ok {
		r0 = rf(ctx, conn, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, openfgav1.OpenFGAServiceClient, string) error); ok {
		r1 = rf(ctx, conn, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FGAStoreHelper_GetStoreIDForTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStoreIDForTenant'
type FGAStoreHelper_GetStoreIDForTenant_Call struct {
	*mock.Call
}

// GetStoreIDForTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - conn openfgav1.OpenFGAServiceClient
//   - tenantID string
func (_e *FGAStoreHelper_Expecter) GetStoreIDForTenant(ctx interface{}, conn interface{}, tenantID interface{}) *FGAStoreHelper_GetStoreIDForTenant_Call {
	return &FGAStoreHelper_GetStoreIDForTenant_Call{Call: _e.mock.On("GetStoreIDForTenant", ctx, conn, tenantID)}
}

func (_c *FGAStoreHelper_GetStoreIDForTenant_Call) Run(run func(ctx context.Context, conn openfgav1.OpenFGAServiceClient, tenantID string)) *FGAStoreHelper_GetStoreIDForTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(openfgav1.OpenFGAServiceClient), args[2].(string))
	})
	return _c
}

func (_c *FGAStoreHelper_GetStoreIDForTenant_Call) Return(_a0 string, _a1 error) *FGAStoreHelper_GetStoreIDForTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FGAStoreHelper_GetStoreIDForTenant_Call) RunAndReturn(run func(context.Context, openfgav1.OpenFGAServiceClient, string) (string, error)) *FGAStoreHelper_GetStoreIDForTenant_Call {
	_c.Call.Return(run)
	return _c
}

// IsDuplicateWriteError provides a mock function with given fields: err
func (_m *FGAStoreHelper) IsDuplicateWriteError(err error) bool {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicateWriteError")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(error) bool); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FGAStoreHelper_IsDuplicateWriteError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicateWriteError'
type FGAStoreHelper_IsDuplicateWriteError_Call struct {
	*mock.Call
}

// IsDuplicateWriteError is a helper method to define mock.On call
//   - err error
func (_e *FGAStoreHelper_Expecter) IsDuplicateWriteError(err interface{}) *FGAStoreHelper_IsDuplicateWriteError_Call {
	return &FGAStoreHelper_IsDuplicateWriteError_Call{Call: _e.mock.On("IsDuplicateWriteError", err)}
}

func (_c *FGAStoreHelper_IsDuplicateWriteError_Call) Run(run func(err error)) *FGAStoreHelper_IsDuplicateWriteError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *FGAStoreHelper_IsDuplicateWriteError_Call) Return(_a0 bool) *FGAStoreHelper_IsDuplicateWriteError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FGAStoreHelper_IsDuplicateWriteError_Call) RunAndReturn(run func(error) bool) *FGAStoreHelper_IsDuplicateWriteError_Call {
	_c.Call.Return(run)
	return _c
}

// NewFGAStoreHelper creates a new instance of FGAStoreHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFGAStoreHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *FGAStoreHelper {
	mock := &FGAStoreHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
