// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

type ClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientFactory) EXPECT() *ClientFactory_Expecter {
	return &ClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function with given fields: ctx, accountPath
func (_m *ClientFactory) New(ctx context.Context, accountPath string) (client.Client, error) {
	ret := _m.Called(ctx, accountPath)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return rf(ctx, accountPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = rf(ctx, accountPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type ClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
//   - accountPath string
func (_e *ClientFactory_Expecter) New(ctx interface{}, accountPath interface{}) *ClientFactory_New_Call {
	return &ClientFactory_New_Call{Call: _e.mock.On("New", ctx, accountPath)}
}

func (_c *ClientFactory_New_Call) Run(run func(ctx context.Context, accountPath string)) *ClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientFactory_New_Call) Return(_a0 client.Client, _a1 error) *ClientFactory_New_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientFactory_New_Call) RunAndReturn(run func(context.Context, string) (client.Client, error)) *ClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientFactory creates a new instance of ClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientFactory {
	mock := &ClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
