/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.platform-mesh.io/iam-service/pkg/graph"
)

// NewIDMUserChecker creates a new instance of IDMUserChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDMUserChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDMUserChecker {
	mock := &IDMUserChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IDMUserChecker is an autogenerated mock type for the IDMUserChecker type
type IDMUserChecker struct {
	mock.Mock
}

type IDMUserChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *IDMUserChecker) EXPECT() *IDMUserChecker_Expecter {
	return &IDMUserChecker_Expecter{mock: &_m.Mock}
}

// UserByMail provides a mock function for the type IDMUserChecker
func (_mock *IDMUserChecker) UserByMail(ctx context.Context, userID string) (*graph.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UserByMail")
	}

	var r0 *graph.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*graph.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *graph.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IDMUserChecker_UserByMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByMail'
type IDMUserChecker_UserByMail_Call struct {
	*mock.Call
}

// UserByMail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *IDMUserChecker_Expecter) UserByMail(ctx interface{}, userID interface{}) *IDMUserChecker_UserByMail_Call {
	return &IDMUserChecker_UserByMail_Call{Call: _e.mock.On("UserByMail", ctx, userID)}
}

func (_c *IDMUserChecker_UserByMail_Call) Run(run func(ctx context.Context, userID string)) *IDMUserChecker_UserByMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IDMUserChecker_UserByMail_Call) Return(user *graph.User, err error) *IDMUserChecker_UserByMail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *IDMUserChecker_UserByMail_Call) RunAndReturn(run func(ctx context.Context, userID string) (*graph.User, error)) *IDMUserChecker_UserByMail_Call {
	_c.Call.Return(run)
	return _c
}
