version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(k8s.io)
      - prefix(github.com/kcp-dev)
    skip-generated: true
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/platform-mesh
          - github.com/spf13
          - sigs.k8s.io
          - github.com/go-logr
          - github.com/kcp-dev
          - k8s.io
          - github.com/gorilla/websocket
          - go.opentelemetry.io
        deny:
          - pkg: io/ioutil
            desc: Use the 'io' and 'os' packages instead.
          - pkg: github.com/stretchr/testify
            desc: Use stdlib testing package in non-test files
  gocritic:
    enabled-checks:
      - importShadow
    disabled-checks:
      - ifElseChain
      - hugeParam
      - exitAfterDefer
  nolintlint:
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - depguard
    - path: test/
      linters:
        - depguard
    - path: cmd/
      linters:
        - depguard
    - path: internal/
      linters:
        - depguard
    - path: pkg/
      linters:
        - depguard
    - path: api/
      linters:
        - depguard
    - linters:
        - staticcheck
      text: "SA1019:"

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(k8s.io)
        - prefix(github.com/kcp-dev)
      skip-generated: true

run:
  allow-parallel-runners: true
