package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/platform-mesh/iam-service/pkg/graph"
)

// AssignRolesToUsers is the resolver for the assignRolesToUsers field.
func (r *mutationResolver) AssignRolesToUsers(ctx context.Context, context graph.ResourceContext, changes []*graph.UserRoleChange) (*graph.RoleAssignmentResult, error) {
	return r.svc.AssignRolesToUsers(ctx, context, changes)
}

// RemoveRole is the resolver for the removeRole field.
func (r *mutationResolver) RemoveRole(ctx context.Context, context graph.ResourceContext, input graph.RemoveRoleInput) (*graph.RoleRemovalResult, error) {
	return r.svc.RemoveRole(ctx, context, input)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, context graph.ResourceContext) ([]*graph.Role, error) {
	return r.svc.Roles(ctx, context)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, context graph.ResourceContext, roleFilters []string, sortBy *graph.SortByInput, page *graph.PageInput) (*graph.UserConnection, error) {
	return r.svc.Users(ctx, context, roleFilters, sortBy, page)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*graph.User, error) {
	return r.svc.User(ctx, userID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*graph.User, error) {
	return r.svc.Me(ctx)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
