apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: certificates.certmanager.ca
  labels:
    ca: cert-manager
spec:
  resource:
    kind: Certificate
    apiGroup: certmanager.ca
    versions: [v1alpha1]
  projection:
    group: identity.generic.platform-mesh.io
  naming:
    namespace: cert-manager-{{.ClusterName}}
  related:
    - identifier: certificate
      origin: service
      kind: Secret
      object:
        reference:
          path: status.relatedResources.secret.name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-syncagent-cert-manager:certificates
rules:
  - apiGroups:
      - certmanager.ca
    resources:
      - certificates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-syncagent-cert-manager:certificates
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-syncagent-cert-manager:certificates
subjects:
  - kind: ServiceAccount
    name: api-syncagent-cert-manager
    namespace: default
