// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/openmfp/iam-service/pkg/graph"

	mock "github.com/stretchr/testify/mock"
)

// UserHooks is an autogenerated mock type for the UserHooks type
type UserHooks struct {
	mock.Mock
}

type UserHooks_Expecter struct {
	mock *mock.Mock
}

func (_m *UserHooks) EXPECT() *UserHooks_Expecter {
	return &UserHooks_Expecter{mock: &_m.Mock}
}

// UserCreated provides a mock function with given fields: ctx, user, tenantID
func (_m *UserHooks) UserCreated(ctx context.Context, user *graph.User, tenantID string) {
	_m.Called(ctx, user, tenantID)
}

// UserHooks_UserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCreated'
type UserHooks_UserCreated_Call struct {
	*mock.Call
}

// UserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - user *graph.User
//   - tenantID string
func (_e *UserHooks_Expecter) UserCreated(ctx interface{}, user interface{}, tenantID interface{}) *UserHooks_UserCreated_Call {
	return &UserHooks_UserCreated_Call{Call: _e.mock.On("UserCreated", ctx, user, tenantID)}
}

func (_c *UserHooks_UserCreated_Call) Run(run func(ctx context.Context, user *graph.User, tenantID string)) *UserHooks_UserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*graph.User), args[2].(string))
	})
	return _c
}

func (_c *UserHooks_UserCreated_Call) Return() *UserHooks_UserCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserHooks_UserCreated_Call) RunAndReturn(run func(context.Context, *graph.User, string)) *UserHooks_UserCreated_Call {
	_c.Call.Return(run)
	return _c
}

// UserInvited provides a mock function with given fields: ctx, user, tenantID, scope, userInvited
func (_m *UserHooks) UserInvited(ctx context.Context, user *graph.User, tenantID string, scope string, userInvited bool) {
	_m.Called(ctx, user, tenantID, scope, userInvited)
}

// UserHooks_UserInvited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInvited'
type UserHooks_UserInvited_Call struct {
	*mock.Call
}

// UserInvited is a helper method to define mock.On call
//   - ctx context.Context
//   - user *graph.User
//   - tenantID string
//   - scope string
//   - userInvited bool
func (_e *UserHooks_Expecter) UserInvited(ctx interface{}, user interface{}, tenantID interface{}, scope interface{}, userInvited interface{}) *UserHooks_UserInvited_Call {
	return &UserHooks_UserInvited_Call{Call: _e.mock.On("UserInvited", ctx, user, tenantID, scope, userInvited)}
}

func (_c *UserHooks_UserInvited_Call) Run(run func(ctx context.Context, user *graph.User, tenantID string, scope string, userInvited bool)) *UserHooks_UserInvited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*graph.User), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *UserHooks_UserInvited_Call) Return() *UserHooks_UserInvited_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserHooks_UserInvited_Call) RunAndReturn(run func(context.Context, *graph.User, string, string, bool)) *UserHooks_UserInvited_Call {
	_c.Call.Return(run)
	return _c
}

// UserRemoved provides a mock function with given fields: ctx, user, tenantID
func (_m *UserHooks) UserRemoved(ctx context.Context, user *graph.User, tenantID string) {
	_m.Called(ctx, user, tenantID)
}

// UserHooks_UserRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRemoved'
type UserHooks_UserRemoved_Call struct {
	*mock.Call
}

// UserRemoved is a helper method to define mock.On call
//   - ctx context.Context
//   - user *graph.User
//   - tenantID string
func (_e *UserHooks_Expecter) UserRemoved(ctx interface{}, user interface{}, tenantID interface{}) *UserHooks_UserRemoved_Call {
	return &UserHooks_UserRemoved_Call{Call: _e.mock.On("UserRemoved", ctx, user, tenantID)}
}

func (_c *UserHooks_UserRemoved_Call) Run(run func(ctx context.Context, user *graph.User, tenantID string)) *UserHooks_UserRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*graph.User), args[2].(string))
	})
	return _c
}

func (_c *UserHooks_UserRemoved_Call) Return() *UserHooks_UserRemoved_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserHooks_UserRemoved_Call) RunAndReturn(run func(context.Context, *graph.User, string)) *UserHooks_UserRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserHooks creates a new instance of UserHooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserHooks {
	mock := &UserHooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
