/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockWorkspaceClientFactory creates a new instance of MockWorkspaceClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceClientFactory {
	mock := &MockWorkspaceClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceClientFactory is an autogenerated mock type for the WorkspaceClientFactory type
type MockWorkspaceClientFactory struct {
	mock.Mock
}

type MockWorkspaceClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceClientFactory) EXPECT() *MockWorkspaceClientFactory_Expecter {
	return &MockWorkspaceClientFactory_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function for the type MockWorkspaceClientFactory
func (_mock *MockWorkspaceClientFactory) GetClient(workspacePath string) (client.Client, error) {
	ret := _mock.Called(workspacePath)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (client.Client, error)); ok {
		return returnFunc(workspacePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) client.Client); ok {
		r0 = returnFunc(workspacePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(workspacePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceClientFactory_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockWorkspaceClientFactory_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - workspacePath string
func (_e *MockWorkspaceClientFactory_Expecter) GetClient(workspacePath interface{}) *MockWorkspaceClientFactory_GetClient_Call {
	return &MockWorkspaceClientFactory_GetClient_Call{Call: _e.mock.On("GetClient", workspacePath)}
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) Run(run func(workspacePath string)) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) Return(client1 client.Client, err error) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) RunAndReturn(run func(workspacePath string) (client.Client, error)) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Return(run)
	return _c
}
