// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkspaceClientFactory is an autogenerated mock type for the WorkspaceClientFactory type
type MockWorkspaceClientFactory struct {
	mock.Mock
}

type MockWorkspaceClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceClientFactory) EXPECT() *MockWorkspaceClientFactory_Expecter {
	return &MockWorkspaceClientFactory_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with given fields: workspacePath
func (_m *MockWorkspaceClientFactory) GetClient(workspacePath string) (client.Client, error) {
	ret := _m.Called(workspacePath)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (client.Client, error)); ok {
		return rf(workspacePath)
	}
	if rf, ok := ret.Get(0).(func(string) client.Client); ok {
		r0 = rf(workspacePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(workspacePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkspaceClientFactory_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockWorkspaceClientFactory_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - workspacePath string
func (_e *MockWorkspaceClientFactory_Expecter) GetClient(workspacePath interface{}) *MockWorkspaceClientFactory_GetClient_Call {
	return &MockWorkspaceClientFactory_GetClient_Call{Call: _e.mock.On("GetClient", workspacePath)}
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) Run(run func(workspacePath string)) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) Return(_a0 client.Client, _a1 error) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkspaceClientFactory_GetClient_Call) RunAndReturn(run func(string) (client.Client, error)) *MockWorkspaceClientFactory_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkspaceClientFactory creates a new instance of MockWorkspaceClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceClientFactory {
	mock := &MockWorkspaceClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
