apiVersion: operator.kcp.io/v1alpha1
kind: RootShard
metadata:
  name: root
  namespace: kcp-comer
spec:
  auth:
    serviceAccount:
      enabled: true
    oidc:
      issuerURL: https://auth.genericcontrolplane.io
      clientID: platform-mesh
      groupsClaim: groups
      usernameClaim: email
      usernamePrefix: "oidc:"
      groupsPrefix: "oidc:"
      clientSecret: Z2Fyc2lha2FsYmlzdmFuZGVuekWplCg==
  external:
    hostname: api.comer.genericcontrolplane.io
    port: 443
    privateHostname: api-internal.comer.genericcontrolplane.io
    privatePort: 6443
  certificates:
    # this references the issuer created above
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: kcp-ca
  cache:
    embedded:
      # kcp comes with a cache server accessible to all shards,
      # in this case it is fine to enable the embedded instance
      enabled: true
  etcd:
    endpoints:
      - https://root-client.kcp-comer.svc.cluster.local:2379
    tlsConfig:
      secretRef:
        name: etcd-ca-tls
  shardBaseURL: https://root.comer.genericcontrolplane.io:6443
  certificateTemplates:
    server:
      spec:
        dnsNames:
        - root.comer.genericcontrolplane.io
  serviceTemplate:
    spec:
      type: LoadBalancer