# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: terminal.platform-mesh.io
spec:
  permissionClaims:
  - group: core.platform-mesh.io
    identityHash: 7748f340fc0b85b16becaf6e9c45258ecf9a367569d085448a7af64be9d321b0
    resource: accountinfos
    verbs:
    - get
    - list
    - watch
  resources:
  - group: terminal.platform-mesh.io
    name: terminals
    schema: v260623-56451538.terminals.terminal.platform-mesh.io
    storage:
      crd: {}
status: {}
