//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebalanceConfig) DeepCopyInto(out *RebalanceConfig) {
	*out = *in
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebalanceConfig.
func (in *RebalanceConfig) DeepCopy() *RebalanceConfig {
	if in == nil {
		return nil
	}
	out := new(RebalanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSharding) DeepCopyInto(out *ResourceSharding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSharding.
func (in *ResourceSharding) DeepCopy() *ResourceSharding {
	if in == nil {
		return nil
	}
	out := new(ResourceSharding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSharding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceShardingList) DeepCopyInto(out *ResourceShardingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceSharding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceShardingList.
func (in *ResourceShardingList) DeepCopy() *ResourceShardingList {
	if in == nil {
		return nil
	}
	out := new(ResourceShardingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceShardingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceShardingSpec) DeepCopyInto(out *ResourceShardingSpec) {
	*out = *in
	out.Target = in.Target
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]ShardRef, len(*in))
		copy(*out, *in)
	}
	out.Rebalance = in.Rebalance
	out.Webhook = in.Webhook
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceShardingSpec.
func (in *ResourceShardingSpec) DeepCopy() *ResourceShardingSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceShardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceShardingStatus) DeepCopyInto(out *ResourceShardingStatus) {
	*out = *in
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = make([]ShardDistribution, len(*in))
		copy(*out, *in)
	}
	if in.LastRebalanceTime != nil {
		in, out := &in.LastRebalanceTime, &out.LastRebalanceTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceShardingStatus.
func (in *ResourceShardingStatus) DeepCopy() *ResourceShardingStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceShardingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDistribution) DeepCopyInto(out *ShardDistribution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDistribution.
func (in *ShardDistribution) DeepCopy() *ShardDistribution {
	if in == nil {
		return nil
	}
	out := new(ShardDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardRef) DeepCopyInto(out *ShardRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardRef.
func (in *ShardRef) DeepCopy() *ShardRef {
	if in == nil {
		return nil
	}
	out := new(ShardRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetResource) DeepCopyInto(out *TargetResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetResource.
func (in *TargetResource) DeepCopy() *TargetResource {
	if in == nil {
		return nil
	}
	out := new(TargetResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}
