// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/platform-mesh/rebac-authz-webhook/pkg/clustercache"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/cluster"
)

// NewClusterCacheProvider creates a new instance of ClusterCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterCacheProvider {
	mock := &ClusterCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterCacheProvider is an autogenerated mock type for the Provider type
type ClusterCacheProvider struct {
	mock.Mock
}

type ClusterCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterCacheProvider) EXPECT() *ClusterCacheProvider_Expecter {
	return &ClusterCacheProvider_Expecter{mock: &_m.Mock}
}

// Engage provides a mock function for the type ClusterCacheProvider
func (_mock *ClusterCacheProvider) Engage(context1 context.Context, s string, cluster1 cluster.Cluster) error {
	ret := _mock.Called(context1, s, cluster1)

	if len(ret) == 0 {
		panic("no return value specified for Engage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, cluster.Cluster) error); ok {
		r0 = returnFunc(context1, s, cluster1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterCacheProvider_Engage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Engage'
type ClusterCacheProvider_Engage_Call struct {
	*mock.Call
}

// Engage is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - cluster1 cluster.Cluster
func (_e *ClusterCacheProvider_Expecter) Engage(context1 interface{}, s interface{}, cluster1 interface{}) *ClusterCacheProvider_Engage_Call {
	return &ClusterCacheProvider_Engage_Call{Call: _e.mock.On("Engage", context1, s, cluster1)}
}

func (_c *ClusterCacheProvider_Engage_Call) Run(run func(context1 context.Context, s string, cluster1 cluster.Cluster)) *ClusterCacheProvider_Engage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 cluster.Cluster
		if args[2] != nil {
			arg2 = args[2].(cluster.Cluster)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClusterCacheProvider_Engage_Call) Return(err error) *ClusterCacheProvider_Engage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterCacheProvider_Engage_Call) RunAndReturn(run func(context1 context.Context, s string, cluster1 cluster.Cluster) error) *ClusterCacheProvider_Engage_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ClusterCacheProvider
func (_mock *ClusterCacheProvider) Get(clusterName string) (clustercache.ClusterInfo, bool) {
	ret := _mock.Called(clusterName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 clustercache.ClusterInfo
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (clustercache.ClusterInfo, bool)); ok {
		return returnFunc(clusterName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) clustercache.ClusterInfo); ok {
		r0 = returnFunc(clusterName)
	} else {
		r0 = ret.Get(0).(clustercache.ClusterInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clusterName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ClusterCacheProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClusterCacheProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - clusterName string
func (_e *ClusterCacheProvider_Expecter) Get(clusterName interface{}) *ClusterCacheProvider_Get_Call {
	return &ClusterCacheProvider_Get_Call{Call: _e.mock.On("Get", clusterName)}
}

func (_c *ClusterCacheProvider_Get_Call) Run(run func(clusterName string)) *ClusterCacheProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterCacheProvider_Get_Call) Return(clusterInfo clustercache.ClusterInfo, b bool) *ClusterCacheProvider_Get_Call {
	_c.Call.Return(clusterInfo, b)
	return _c
}

func (_c *ClusterCacheProvider_Get_Call) RunAndReturn(run func(clusterName string) (clustercache.ClusterInfo, bool)) *ClusterCacheProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type ClusterCacheProvider
func (_mock *ClusterCacheProvider) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClusterCacheProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ClusterCacheProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *ClusterCacheProvider_Expecter) Start(context1 interface{}) *ClusterCacheProvider_Start_Call {
	return &ClusterCacheProvider_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *ClusterCacheProvider_Start_Call) Run(run func(context1 context.Context)) *ClusterCacheProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClusterCacheProvider_Start_Call) Return(err error) *ClusterCacheProvider_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClusterCacheProvider_Start_Call) RunAndReturn(run func(context1 context.Context) error) *ClusterCacheProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}
