apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- deployment.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/resource-broker
  newTag: latest@sha256:63dc9e55cee9c3a71663be1c5166074b55c769d47758800df0fb2603f3b56ca8
