apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resource-broker-system
resources:
- ../crd
- ../rbac
- deployment.yaml

images:
- name: broker
  newName: ghcr.io/platform-mesh/resource-broker
  newTag: latest@sha256:16d551dd074d6c6694efaebfd193aff851d01a7e2dfd8e72c21e0b20017d2559
