// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

// Holds additional information about the retrieved data
type PageInfo struct {
	Count           int  `json:"count"`
	TotalCount      int  `json:"totalCount"`
	HasNextPage     bool `json:"hasNextPage"`
	HasPreviousPage bool `json:"hasPreviousPage"`
}

type PageInput struct {
	Limit *int `json:"limit,omitempty"`
	Page  *int `json:"page,omitempty"`
}

type Query struct {
}

// Input for removing a role from a user
type RemoveRoleInput struct {
	UserID string `json:"userId"`
	Role   string `json:"role"`
}

type Resource struct {
	Name      string  `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
}

// Common resource context used across queries and mutations
type ResourceContext struct {
	Group       string    `json:"group"`
	Kind        string    `json:"kind"`
	Resource    *Resource `json:"resource"`
	AccountPath string    `json:"accountPath"`
}

// Represents a role that can be granted to a user or group of users
type Role struct {
	//  Is the unique identifier of the role
	ID string `json:"id"`
	//  Is a human readable name of the role
	DisplayName string `json:"displayName"`
	//  Is a description of what the role provides
	Description string `json:"description"`
}

// Result of role assignment operation
type RoleAssignmentResult struct {
	Success       bool     `json:"success"`
	Errors        []string `json:"errors,omitempty"`
	AssignedCount int      `json:"assignedCount"`
}

// Result of role removal operation
type RoleRemovalResult struct {
	Success     bool    `json:"success"`
	Error       *string `json:"error,omitempty"`
	WasAssigned bool    `json:"wasAssigned"`
}

type SortByInput struct {
	Field     UserSortField `json:"field"`
	Direction SortDirection `json:"direction"`
}

// Represents a user
type User struct {
	UserID    string  `json:"userId"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

// Is a list of the users and their roles
type UserConnection struct {
	Users []*UserRoles `json:"users"`
	//  number of granted users in the list
	PageInfo *PageInfo `json:"pageInfo"`
}

// Holds information about a specific user and a list of roles that should be assigned to the user
type UserRoleChange struct {
	UserID string   `json:"userId"`
	Roles  []string `json:"roles"`
}

// Contains all roles that are granted to a user
type UserRoles struct {
	User  *User   `json:"user"`
	Roles []*Role `json:"roles"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserSortField string

const (
	UserSortFieldUserID    UserSortField = "userId"
	UserSortFieldEmail     UserSortField = "email"
	UserSortFieldFirstName UserSortField = "firstName"
	UserSortFieldLastName  UserSortField = "lastName"
)

var AllUserSortField = []UserSortField{
	UserSortFieldUserID,
	UserSortFieldEmail,
	UserSortFieldFirstName,
	UserSortFieldLastName,
}

func (e UserSortField) IsValid() bool {
	switch e {
	case UserSortFieldUserID, UserSortFieldEmail, UserSortFieldFirstName, UserSortFieldLastName:
		return true
	}
	return false
}

func (e UserSortField) String() string {
	return string(e)
}

func (e *UserSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserSortField", str)
	}
	return nil
}

func (e UserSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
