package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
)

// InviteUser is the resolver for the inviteUser field.
func (r *mutationResolver) InviteUser(ctx context.Context, tenantID string, invite Invite, notifyByEmail bool) (bool, error) {
	panic(fmt.Errorf("not implemented: InviteUser - inviteUser"))
}

// DeleteInvite is the resolver for the deleteInvite field.
func (r *mutationResolver) DeleteInvite(ctx context.Context, tenantID string, invite Invite) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteInvite - deleteInvite"))
}

// AssignRoleBindings is the resolver for the assignRoleBindings field.
func (r *mutationResolver) AssignRoleBindings(ctx context.Context, tenantID string, entityType string, entityID string, input []*Change) (bool, error) {
	panic(fmt.Errorf("not implemented: AssignRoleBindings - assignRoleBindings"))
}

// RemoveFromEntity is the resolver for the removeFromEntity field.
func (r *mutationResolver) RemoveFromEntity(ctx context.Context, tenantID string, entityType string, userID string, entityID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveFromEntity - removeFromEntity"))
}

// LeaveEntity is the resolver for the leaveEntity field.
func (r *mutationResolver) LeaveEntity(ctx context.Context, tenantID string, entityType string, entityID string) (bool, error) {
	panic(fmt.Errorf("not implemented: LeaveEntity - leaveEntity"))
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, tenantID string, entityType string, entityID string, owner string) (bool, error) {
	panic(fmt.Errorf("not implemented: CreateAccount - createAccount"))
}

// RemoveAccount is the resolver for the removeAccount field.
func (r *mutationResolver) RemoveAccount(ctx context.Context, tenantID string, entityType string, entityID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveAccount - removeAccount"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, tenantID string, input UserInput) (*User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// RemoveUser is the resolver for the removeUser field.
func (r *mutationResolver) RemoveUser(ctx context.Context, tenantID string, userID *string, email *string) (*bool, error) {
	panic(fmt.Errorf("not implemented: RemoveUser - removeUser"))
}

// UsersOfEntity is the resolver for the usersOfEntity field.
func (r *queryResolver) UsersOfEntity(ctx context.Context, tenantID string, entity EntityInput, limit *int, page *int, showInvitees *bool) (*GrantedUserConnection, error) {
	panic(fmt.Errorf("not implemented: UsersOfEntity - usersOfEntity"))
}

// RolesForUserOfEntity is the resolver for the rolesForUserOfEntity field.
func (r *queryResolver) RolesForUserOfEntity(ctx context.Context, tenantID string, entity EntityInput, userID string) ([]*Role, error) {
	panic(fmt.Errorf("not implemented: RolesForUserOfEntity - rolesForUserOfEntity"))
}

// AvailableRolesForEntity is the resolver for the availableRolesForEntity field.
func (r *queryResolver) AvailableRolesForEntity(ctx context.Context, tenantID string, entity EntityInput) ([]*Role, error) {
	panic(fmt.Errorf("not implemented: AvailableRolesForEntity - availableRolesForEntity"))
}

// AvailableRolesForEntityType is the resolver for the availableRolesForEntityType field.
func (r *queryResolver) AvailableRolesForEntityType(ctx context.Context, tenantID string, entityType string) ([]*Role, error) {
	panic(fmt.Errorf("not implemented: AvailableRolesForEntityType - availableRolesForEntityType"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, tenantID string, userID string) (*User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, tenantID string, email string) (*User, error) {
	panic(fmt.Errorf("not implemented: UserByEmail - userByEmail"))
}

// UsersConnection is the resolver for the usersConnection field.
func (r *queryResolver) UsersConnection(ctx context.Context, tenantID string, limit *int, page *int) (*UserConnection, error) {
	panic(fmt.Errorf("not implemented: UsersConnection - usersConnection"))
}

// ZoneByZoneID is the resolver for the zoneByZoneId field.
func (r *queryResolver) ZoneByZoneID(ctx context.Context, zoneID string) (*Zone, error) {
	panic(fmt.Errorf("not implemented: ZoneByZoneID - zoneByZoneId"))
}

// TenantInfo is the resolver for the tenantInfo field.
func (r *queryResolver) TenantInfo(ctx context.Context, tenantID *string) (*TenantInfo, error) {
	panic(fmt.Errorf("not implemented: TenantInfo - tenantInfo"))
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, tenantID string, limit *int, page *int) (*TeamConnection, error) {
	panic(fmt.Errorf("not implemented: Teams - teams"))
}

// TeamByName is the resolver for the teamByName field.
func (r *queryResolver) TeamByName(ctx context.Context, tenantID string, teamName string) (*Team, error) {
	panic(fmt.Errorf("not implemented: TeamByName - teamByName"))
}

// ChildTeams is the resolver for the childTeams field.
func (r *teamResolver) ChildTeams(ctx context.Context, obj *Team, limit *int, page *int) (*TeamConnection, error) {
	panic(fmt.Errorf("not implemented: ChildTeams - childTeams"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Team returns TeamResolver implementation.
func (r *Resolver) Team() TeamResolver { return &teamResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type teamResolver struct{ *Resolver }
