apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: acceptapis
spec:
  resources:
    - group: broker.platform-mesh.io
      name: acceptapis
      schema: current.acceptapis.broker.platform-mesh.io
  permissionClaims:
    - resource: secrets
      verbs:
        - get
        - list
        - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acceptapis-apiexport-bind
rules:
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports
    verbs:
      - bind
    resourceNames:
      - acceptapis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acceptapis-anonymous-bind
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acceptapis-apiexport-bind
  apiGroup: rbac.authorization.k8s.io
