apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: marketplace.platform-mesh.io
spec:
  resources:
  - group: marketplace.platform-mesh.io
    name: marketplaceentries
    schema: v260623-482e10b2.marketplaceentries.marketplace.platform-mesh.io
    storage:
      crd: {}
status: {}
