apiVersion: operator.broker.platform-mesh.io/v1alpha1
kind: Broker
metadata:
  name: resource-broker
  namespace: resource-broker-system
spec:
  image:
    repository: resource-broker-kcp
    tag: platform-mesh
  hostAliases:
    - ip: 10.96.188.4 # hardcoded in pm local-setup
      hostnames:
        - localhost
  extraArgs:
    - "-kubeconfig=/kubeconfig/kubeconfig"
    - "-kcp-kubeconfig=/kubeconfig/kubeconfig"
    - "-acceptapi=acceptapis"
    - "-brokerapi=generic.platform-mesh.io"
    - "-zap-devel=true"
    - "-zap-log-level=debug"
    - "-watch-kind=Certificate.v1alpha1.identity.generic.platform-mesh.io"
  volumes:
    - name: kubeconfig-volume
      secret:
        secretName: kcp-kubeconfig
  volumeMounts:
    - name: kubeconfig-volume
      mountPath: /kubeconfig
      readOnly: true
