version: '3'

vars:
  LOCAL_BIN: bin
  MOCKERY_VERSION: v3.6.4
  GO_TEST_COVERAGE_VERSION: v2.17.1
tasks:
  ## Setup
  setup:mockery:
    internal: true
    cmds:
      - '{{.LOCAL_BIN}}/mockery version 2>/dev/null | grep -q {{.MOCKERY_VERSION}} || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/vektra/mockery/v3@{{.MOCKERY_VERSION}}'
  setup:golangci-lint:
    internal: true
    cmds:
      - test -s {{.LOCAL_BIN}}/golangci-lint || GOBIN=$(pwd)/{{.LOCAL_BIN}} go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  ## Development
  mockery:
    deps: [setup:mockery]
    cmds:
      - "{{.LOCAL_BIN}}/mockery"
  fmt:
    cmds:
      - go fmt ./...
  lint:
    deps: [setup:golangci-lint, mockery]
    cmds:
      - task: fmt
      - "{{.LOCAL_BIN}}/golangci-lint run --timeout 15m ./..."
  build:
    cmds:
      - go build ./...
  test:
    env:
      GO111MODULE: on
    deps:
      - task: mockery
    cmds:
      - go clean -testcache
      - go test ./...
  cover:
    desc: Run tests with coverage
    deps:
      - task: mockery
    cmds:
      - go clean -testcache
      - go test -coverprofile=cover.out -covermode=atomic -coverpkg=./... ./...
  test-coverage:
    desc: Run tests with coverage and check thresholds
    deps:
      - task: cover
    cmds:
      - go install github.com/vladopajic/go-test-coverage/v2@{{.GO_TEST_COVERAGE_VERSION}}
      - go-test-coverage --profile cover.out --config ./.testcoverage.yml
