---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apis.kcp.io
  resources:
  - apibindings
  - apiexports
  - apiresourceschemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kcp.io
  resources:
  - logicalclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - accountinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - searchindices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - searchindices/finalizers
  verbs:
  - update
- apiGroups:
  - core.platform-mesh.io
  resources:
  - searchindices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenancy.kcp.io
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
