threshold:
  file: 80
  package: 80
  total: 80
exclude:
  paths:
    - ^pkg/handler/mocks # exclude generated mock files
    - main\.go$ # skip covering main.go
    - ^cmd # skip covering cmd directory
    - ^pkg/authorization/response\.go$
    - ^pkg/util
    - ^pkg/config
