# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        authorization-mode: "RBAC,Webhook"
        authorization-webhook-config-file: "/config/authz.yaml"
        authorization-webhook-cache-authorized-ttl: "1s" # only so low for testing
        authorization-webhook-cache-unauthorized-ttl: "1s" # only so low for testing
        authorization-webhook-version: v1

      extraVolumes:
      - name: api-server-basic-auth-files
        hostPath: "/config"
        mountPath: "/config"
        readOnly: true
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/I547291/Documents/Development/ams-pro/authz-webook/config
    containerPath: /config
