// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/openmfp/iam-service/pkg/layers/core/models"
)

// Hooks is an autogenerated mock type for the Hooks type
type Hooks struct {
	mock.Mock
}

type Hooks_Expecter struct {
	mock *mock.Mock
}

func (_m *Hooks) EXPECT() *Hooks_Expecter {
	return &Hooks_Expecter{mock: &_m.Mock}
}

// UserCreated provides a mock function with given fields: ctx, params
func (_m *Hooks) UserCreated(ctx context.Context, params models.User) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UserCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Hooks_UserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserCreated'
type Hooks_UserCreated_Call struct {
	*mock.Call
}

// UserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.User
func (_e *Hooks_Expecter) UserCreated(ctx interface{}, params interface{}) *Hooks_UserCreated_Call {
	return &Hooks_UserCreated_Call{Call: _e.mock.On("UserCreated", ctx, params)}
}

func (_c *Hooks_UserCreated_Call) Run(run func(ctx context.Context, params models.User)) *Hooks_UserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Hooks_UserCreated_Call) Return(_a0 error) *Hooks_UserCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hooks_UserCreated_Call) RunAndReturn(run func(context.Context, models.User) error) *Hooks_UserCreated_Call {
	_c.Call.Return(run)
	return _c
}

// NewHooks creates a new instance of Hooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hooks {
	mock := &Hooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
