// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/openmfp/iam-service/pkg/layers/core/models"
	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// VerifyCreateUserInput provides a mock function with given fields: ctx, params
func (_m *Interface) VerifyCreateUserInput(ctx context.Context, params models.User) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCreateUserInput")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Interface_VerifyCreateUserInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCreateUserInput'
type Interface_VerifyCreateUserInput_Call struct {
	*mock.Call
}

// VerifyCreateUserInput is a helper method to define mock.On call
//   - ctx context.Context
//   - params models.User
func (_e *Interface_Expecter) VerifyCreateUserInput(ctx interface{}, params interface{}) *Interface_VerifyCreateUserInput_Call {
	return &Interface_VerifyCreateUserInput_Call{Call: _e.mock.On("VerifyCreateUserInput", ctx, params)}
}

func (_c *Interface_VerifyCreateUserInput_Call) Run(run func(ctx context.Context, params models.User)) *Interface_VerifyCreateUserInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Interface_VerifyCreateUserInput_Call) Return(_a0 error) *Interface_VerifyCreateUserInput_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Interface_VerifyCreateUserInput_Call) RunAndReturn(run func(context.Context, models.User) error) *Interface_VerifyCreateUserInput_Call {
	_c.Call.Return(run)
	return _c
}

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
