// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/openmfp/iam-service/pkg/graph"
	mock "github.com/stretchr/testify/mock"
)

// MutationResolver is an autogenerated mock type for the MutationResolver type
type MutationResolver struct {
	mock.Mock
}

type MutationResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MutationResolver) EXPECT() *MutationResolver_Expecter {
	return &MutationResolver_Expecter{mock: &_m.Mock}
}

// AssignRoleBindings provides a mock function with given fields: ctx, tenantID, entityType, entityID, input
func (_m *MutationResolver) AssignRoleBindings(ctx context.Context, tenantID string, entityType string, entityID string, input []*graph.Change) (bool, error) {
	ret := _m.Called(ctx, tenantID, entityType, entityID, input)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleBindings")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []*graph.Change) (bool, error)); ok {
		return rf(ctx, tenantID, entityType, entityID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []*graph.Change) bool); ok {
		r0 = rf(ctx, tenantID, entityType, entityID, input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []*graph.Change) error); ok {
		r1 = rf(ctx, tenantID, entityType, entityID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_AssignRoleBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleBindings'
type MutationResolver_AssignRoleBindings_Call struct {
	*mock.Call
}

// AssignRoleBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
//   - input []*graph.Change
func (_e *MutationResolver_Expecter) AssignRoleBindings(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}, input interface{}) *MutationResolver_AssignRoleBindings_Call {
	return &MutationResolver_AssignRoleBindings_Call{Call: _e.mock.On("AssignRoleBindings", ctx, tenantID, entityType, entityID, input)}
}

func (_c *MutationResolver_AssignRoleBindings_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string, input []*graph.Change)) *MutationResolver_AssignRoleBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]*graph.Change))
	})
	return _c
}

func (_c *MutationResolver_AssignRoleBindings_Call) Return(_a0 bool, _a1 error) *MutationResolver_AssignRoleBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_AssignRoleBindings_Call) RunAndReturn(run func(context.Context, string, string, string, []*graph.Change) (bool, error)) *MutationResolver_AssignRoleBindings_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function with given fields: ctx, tenantID, entityType, entityID, owner
func (_m *MutationResolver) CreateAccount(ctx context.Context, tenantID string, entityType string, entityID string, owner string) (bool, error) {
	ret := _m.Called(ctx, tenantID, entityType, entityID, owner)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (bool, error)); ok {
		return rf(ctx, tenantID, entityType, entityID, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) bool); ok {
		r0 = rf(ctx, tenantID, entityType, entityID, owner)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, entityType, entityID, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MutationResolver_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
//   - owner string
func (_e *MutationResolver_Expecter) CreateAccount(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}, owner interface{}) *MutationResolver_CreateAccount_Call {
	return &MutationResolver_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, tenantID, entityType, entityID, owner)}
}

func (_c *MutationResolver_CreateAccount_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string, owner string)) *MutationResolver_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MutationResolver_CreateAccount_Call) Return(_a0 bool, _a1 error) *MutationResolver_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_CreateAccount_Call) RunAndReturn(run func(context.Context, string, string, string, string) (bool, error)) *MutationResolver_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, tenantID, input
func (_m *MutationResolver) CreateUser(ctx context.Context, tenantID string, input graph.UserInput) (*graph.User, error) {
	ret := _m.Called(ctx, tenantID, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *graph.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.UserInput) (*graph.User, error)); ok {
		return rf(ctx, tenantID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.UserInput) *graph.User); ok {
		r0 = rf(ctx, tenantID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, graph.UserInput) error); ok {
		r1 = rf(ctx, tenantID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MutationResolver_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - input graph.UserInput
func (_e *MutationResolver_Expecter) CreateUser(ctx interface{}, tenantID interface{}, input interface{}) *MutationResolver_CreateUser_Call {
	return &MutationResolver_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, tenantID, input)}
}

func (_c *MutationResolver_CreateUser_Call) Run(run func(ctx context.Context, tenantID string, input graph.UserInput)) *MutationResolver_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(graph.UserInput))
	})
	return _c
}

func (_c *MutationResolver_CreateUser_Call) Return(_a0 *graph.User, _a1 error) *MutationResolver_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_CreateUser_Call) RunAndReturn(run func(context.Context, string, graph.UserInput) (*graph.User, error)) *MutationResolver_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvite provides a mock function with given fields: ctx, tenantID, invite
func (_m *MutationResolver) DeleteInvite(ctx context.Context, tenantID string, invite graph.Invite) (bool, error) {
	ret := _m.Called(ctx, tenantID, invite)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvite")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.Invite) (bool, error)); ok {
		return rf(ctx, tenantID, invite)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.Invite) bool); ok {
		r0 = rf(ctx, tenantID, invite)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, graph.Invite) error); ok {
		r1 = rf(ctx, tenantID, invite)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_DeleteInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvite'
type MutationResolver_DeleteInvite_Call struct {
	*mock.Call
}

// DeleteInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invite graph.Invite
func (_e *MutationResolver_Expecter) DeleteInvite(ctx interface{}, tenantID interface{}, invite interface{}) *MutationResolver_DeleteInvite_Call {
	return &MutationResolver_DeleteInvite_Call{Call: _e.mock.On("DeleteInvite", ctx, tenantID, invite)}
}

func (_c *MutationResolver_DeleteInvite_Call) Run(run func(ctx context.Context, tenantID string, invite graph.Invite)) *MutationResolver_DeleteInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(graph.Invite))
	})
	return _c
}

func (_c *MutationResolver_DeleteInvite_Call) Return(_a0 bool, _a1 error) *MutationResolver_DeleteInvite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_DeleteInvite_Call) RunAndReturn(run func(context.Context, string, graph.Invite) (bool, error)) *MutationResolver_DeleteInvite_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUser provides a mock function with given fields: ctx, tenantID, invite, notifyByEmail
func (_m *MutationResolver) InviteUser(ctx context.Context, tenantID string, invite graph.Invite, notifyByEmail bool) (bool, error) {
	ret := _m.Called(ctx, tenantID, invite, notifyByEmail)

	if len(ret) == 0 {
		panic("no return value specified for InviteUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.Invite, bool) (bool, error)); ok {
		return rf(ctx, tenantID, invite, notifyByEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, graph.Invite, bool) bool); ok {
		r0 = rf(ctx, tenantID, invite, notifyByEmail)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, graph.Invite, bool) error); ok {
		r1 = rf(ctx, tenantID, invite, notifyByEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_InviteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUser'
type MutationResolver_InviteUser_Call struct {
	*mock.Call
}

// InviteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - invite graph.Invite
//   - notifyByEmail bool
func (_e *MutationResolver_Expecter) InviteUser(ctx interface{}, tenantID interface{}, invite interface{}, notifyByEmail interface{}) *MutationResolver_InviteUser_Call {
	return &MutationResolver_InviteUser_Call{Call: _e.mock.On("InviteUser", ctx, tenantID, invite, notifyByEmail)}
}

func (_c *MutationResolver_InviteUser_Call) Run(run func(ctx context.Context, tenantID string, invite graph.Invite, notifyByEmail bool)) *MutationResolver_InviteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(graph.Invite), args[3].(bool))
	})
	return _c
}

func (_c *MutationResolver_InviteUser_Call) Return(_a0 bool, _a1 error) *MutationResolver_InviteUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_InviteUser_Call) RunAndReturn(run func(context.Context, string, graph.Invite, bool) (bool, error)) *MutationResolver_InviteUser_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveEntity provides a mock function with given fields: ctx, tenantID, entityType, entityID
func (_m *MutationResolver) LeaveEntity(ctx context.Context, tenantID string, entityType string, entityID string) (bool, error) {
	ret := _m.Called(ctx, tenantID, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveEntity")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, tenantID, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, tenantID, entityType, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_LeaveEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveEntity'
type MutationResolver_LeaveEntity_Call struct {
	*mock.Call
}

// LeaveEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
func (_e *MutationResolver_Expecter) LeaveEntity(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}) *MutationResolver_LeaveEntity_Call {
	return &MutationResolver_LeaveEntity_Call{Call: _e.mock.On("LeaveEntity", ctx, tenantID, entityType, entityID)}
}

func (_c *MutationResolver_LeaveEntity_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string)) *MutationResolver_LeaveEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MutationResolver_LeaveEntity_Call) Return(_a0 bool, _a1 error) *MutationResolver_LeaveEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_LeaveEntity_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *MutationResolver_LeaveEntity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAccount provides a mock function with given fields: ctx, tenantID, entityType, entityID
func (_m *MutationResolver) RemoveAccount(ctx context.Context, tenantID string, entityType string, entityID string) (bool, error) {
	ret := _m.Called(ctx, tenantID, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAccount")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, tenantID, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, tenantID, entityType, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_RemoveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAccount'
type MutationResolver_RemoveAccount_Call struct {
	*mock.Call
}

// RemoveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - entityID string
func (_e *MutationResolver_Expecter) RemoveAccount(ctx interface{}, tenantID interface{}, entityType interface{}, entityID interface{}) *MutationResolver_RemoveAccount_Call {
	return &MutationResolver_RemoveAccount_Call{Call: _e.mock.On("RemoveAccount", ctx, tenantID, entityType, entityID)}
}

func (_c *MutationResolver_RemoveAccount_Call) Run(run func(ctx context.Context, tenantID string, entityType string, entityID string)) *MutationResolver_RemoveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MutationResolver_RemoveAccount_Call) Return(_a0 bool, _a1 error) *MutationResolver_RemoveAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_RemoveAccount_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *MutationResolver_RemoveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromEntity provides a mock function with given fields: ctx, tenantID, entityType, userID, entityID
func (_m *MutationResolver) RemoveFromEntity(ctx context.Context, tenantID string, entityType string, userID string, entityID string) (bool, error) {
	ret := _m.Called(ctx, tenantID, entityType, userID, entityID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromEntity")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (bool, error)); ok {
		return rf(ctx, tenantID, entityType, userID, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) bool); ok {
		r0 = rf(ctx, tenantID, entityType, userID, entityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, entityType, userID, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_RemoveFromEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromEntity'
type MutationResolver_RemoveFromEntity_Call struct {
	*mock.Call
}

// RemoveFromEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - entityType string
//   - userID string
//   - entityID string
func (_e *MutationResolver_Expecter) RemoveFromEntity(ctx interface{}, tenantID interface{}, entityType interface{}, userID interface{}, entityID interface{}) *MutationResolver_RemoveFromEntity_Call {
	return &MutationResolver_RemoveFromEntity_Call{Call: _e.mock.On("RemoveFromEntity", ctx, tenantID, entityType, userID, entityID)}
}

func (_c *MutationResolver_RemoveFromEntity_Call) Run(run func(ctx context.Context, tenantID string, entityType string, userID string, entityID string)) *MutationResolver_RemoveFromEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MutationResolver_RemoveFromEntity_Call) Return(_a0 bool, _a1 error) *MutationResolver_RemoveFromEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_RemoveFromEntity_Call) RunAndReturn(run func(context.Context, string, string, string, string) (bool, error)) *MutationResolver_RemoveFromEntity_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUser provides a mock function with given fields: ctx, tenantID, userID, email
func (_m *MutationResolver) RemoveUser(ctx context.Context, tenantID string, userID *string, email *string) (*bool, error) {
	ret := _m.Called(ctx, tenantID, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 *bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) (*bool, error)); ok {
		return rf(ctx, tenantID, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) *bool); ok {
		r0 = rf(ctx, tenantID, userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string) error); ok {
		r1 = rf(ctx, tenantID, userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MutationResolver_RemoveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUser'
type MutationResolver_RemoveUser_Call struct {
	*mock.Call
}

// RemoveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - userID *string
//   - email *string
func (_e *MutationResolver_Expecter) RemoveUser(ctx interface{}, tenantID interface{}, userID interface{}, email interface{}) *MutationResolver_RemoveUser_Call {
	return &MutationResolver_RemoveUser_Call{Call: _e.mock.On("RemoveUser", ctx, tenantID, userID, email)}
}

func (_c *MutationResolver_RemoveUser_Call) Run(run func(ctx context.Context, tenantID string, userID *string, email *string)) *MutationResolver_RemoveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MutationResolver_RemoveUser_Call) Return(_a0 *bool, _a1 error) *MutationResolver_RemoveUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MutationResolver_RemoveUser_Call) RunAndReturn(run func(context.Context, string, *string, *string) (*bool, error)) *MutationResolver_RemoveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMutationResolver creates a new instance of MutationResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMutationResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MutationResolver {
	mock := &MutationResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
