/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/openapi"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Paths provides a mock function for the type MockClient
func (_mock *MockClient) Paths() (map[string]openapi.GroupVersion, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Paths")
	}

	var r0 map[string]openapi.GroupVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]openapi.GroupVersion, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]openapi.GroupVersion); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]openapi.GroupVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Paths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Paths'
type MockClient_Paths_Call struct {
	*mock.Call
}

// Paths is a helper method to define mock.On call
func (_e *MockClient_Expecter) Paths() *MockClient_Paths_Call {
	return &MockClient_Paths_Call{Call: _e.mock.On("Paths")}
}

func (_c *MockClient_Paths_Call) Run(run func()) *MockClient_Paths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Paths_Call) Return(stringToGroupVersion map[string]openapi.GroupVersion, err error) *MockClient_Paths_Call {
	_c.Call.Return(stringToGroupVersion, err)
	return _c
}

func (_c *MockClient_Paths_Call) RunAndReturn(run func() (map[string]openapi.GroupVersion, error)) *MockClient_Paths_Call {
	_c.Call.Return(run)
	return _c
}
