/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// NewMockRESTMapper creates a new instance of MockRESTMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRESTMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRESTMapper {
	mock := &MockRESTMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRESTMapper is an autogenerated mock type for the RESTMapper type
type MockRESTMapper struct {
	mock.Mock
}

type MockRESTMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRESTMapper) EXPECT() *MockRESTMapper_Expecter {
	return &MockRESTMapper_Expecter{mock: &_m.Mock}
}

// KindFor provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) KindFor(resource schema.GroupVersionResource) (schema.GroupVersionKind, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for KindFor")
	}

	var r0 schema.GroupVersionKind
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) (schema.GroupVersionKind, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) schema.GroupVersionKind); ok {
		r0 = returnFunc(resource)
	} else {
		r0 = ret.Get(0).(schema.GroupVersionKind)
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_KindFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KindFor'
type MockRESTMapper_KindFor_Call struct {
	*mock.Call
}

// KindFor is a helper method to define mock.On call
//   - resource schema.GroupVersionResource
func (_e *MockRESTMapper_Expecter) KindFor(resource interface{}) *MockRESTMapper_KindFor_Call {
	return &MockRESTMapper_KindFor_Call{Call: _e.mock.On("KindFor", resource)}
}

func (_c *MockRESTMapper_KindFor_Call) Run(run func(resource schema.GroupVersionResource)) *MockRESTMapper_KindFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRESTMapper_KindFor_Call) Return(groupVersionKind schema.GroupVersionKind, err error) *MockRESTMapper_KindFor_Call {
	_c.Call.Return(groupVersionKind, err)
	return _c
}

func (_c *MockRESTMapper_KindFor_Call) RunAndReturn(run func(resource schema.GroupVersionResource) (schema.GroupVersionKind, error)) *MockRESTMapper_KindFor_Call {
	_c.Call.Return(run)
	return _c
}

// KindsFor provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) KindsFor(resource schema.GroupVersionResource) ([]schema.GroupVersionKind, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for KindsFor")
	}

	var r0 []schema.GroupVersionKind
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) ([]schema.GroupVersionKind, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) []schema.GroupVersionKind); ok {
		r0 = returnFunc(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schema.GroupVersionKind)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_KindsFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KindsFor'
type MockRESTMapper_KindsFor_Call struct {
	*mock.Call
}

// KindsFor is a helper method to define mock.On call
//   - resource schema.GroupVersionResource
func (_e *MockRESTMapper_Expecter) KindsFor(resource interface{}) *MockRESTMapper_KindsFor_Call {
	return &MockRESTMapper_KindsFor_Call{Call: _e.mock.On("KindsFor", resource)}
}

func (_c *MockRESTMapper_KindsFor_Call) Run(run func(resource schema.GroupVersionResource)) *MockRESTMapper_KindsFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRESTMapper_KindsFor_Call) Return(groupVersionKinds []schema.GroupVersionKind, err error) *MockRESTMapper_KindsFor_Call {
	_c.Call.Return(groupVersionKinds, err)
	return _c
}

func (_c *MockRESTMapper_KindsFor_Call) RunAndReturn(run func(resource schema.GroupVersionResource) ([]schema.GroupVersionKind, error)) *MockRESTMapper_KindsFor_Call {
	_c.Call.Return(run)
	return _c
}

// RESTMapping provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) RESTMapping(gk schema.GroupKind, versions ...string) (*meta.RESTMapping, error) {
	var tmpRet mock.Arguments
	if len(versions) > 0 {
		tmpRet = _mock.Called(gk, versions)
	} else {
		tmpRet = _mock.Called(gk)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RESTMapping")
	}

	var r0 *meta.RESTMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) (*meta.RESTMapping, error)); ok {
		return returnFunc(gk, versions...)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) *meta.RESTMapping); ok {
		r0 = returnFunc(gk, versions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.RESTMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupKind, ...string) error); ok {
		r1 = returnFunc(gk, versions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_RESTMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTMapping'
type MockRESTMapper_RESTMapping_Call struct {
	*mock.Call
}

// RESTMapping is a helper method to define mock.On call
//   - gk schema.GroupKind
//   - versions ...string
func (_e *MockRESTMapper_Expecter) RESTMapping(gk interface{}, versions ...interface{}) *MockRESTMapper_RESTMapping_Call {
	return &MockRESTMapper_RESTMapping_Call{Call: _e.mock.On("RESTMapping",
		append([]interface{}{gk}, versions...)...)}
}

func (_c *MockRESTMapper_RESTMapping_Call) Run(run func(gk schema.GroupKind, versions ...string)) *MockRESTMapper_RESTMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupKind
		if args[0] != nil {
			arg0 = args[0].(schema.GroupKind)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRESTMapper_RESTMapping_Call) Return(rESTMapping *meta.RESTMapping, err error) *MockRESTMapper_RESTMapping_Call {
	_c.Call.Return(rESTMapping, err)
	return _c
}

func (_c *MockRESTMapper_RESTMapping_Call) RunAndReturn(run func(gk schema.GroupKind, versions ...string) (*meta.RESTMapping, error)) *MockRESTMapper_RESTMapping_Call {
	_c.Call.Return(run)
	return _c
}

// RESTMappings provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) RESTMappings(gk schema.GroupKind, versions ...string) ([]*meta.RESTMapping, error) {
	var tmpRet mock.Arguments
	if len(versions) > 0 {
		tmpRet = _mock.Called(gk, versions)
	} else {
		tmpRet = _mock.Called(gk)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RESTMappings")
	}

	var r0 []*meta.RESTMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) ([]*meta.RESTMapping, error)); ok {
		return returnFunc(gk, versions...)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupKind, ...string) []*meta.RESTMapping); ok {
		r0 = returnFunc(gk, versions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*meta.RESTMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupKind, ...string) error); ok {
		r1 = returnFunc(gk, versions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_RESTMappings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTMappings'
type MockRESTMapper_RESTMappings_Call struct {
	*mock.Call
}

// RESTMappings is a helper method to define mock.On call
//   - gk schema.GroupKind
//   - versions ...string
func (_e *MockRESTMapper_Expecter) RESTMappings(gk interface{}, versions ...interface{}) *MockRESTMapper_RESTMappings_Call {
	return &MockRESTMapper_RESTMappings_Call{Call: _e.mock.On("RESTMappings",
		append([]interface{}{gk}, versions...)...)}
}

func (_c *MockRESTMapper_RESTMappings_Call) Run(run func(gk schema.GroupKind, versions ...string)) *MockRESTMapper_RESTMappings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupKind
		if args[0] != nil {
			arg0 = args[0].(schema.GroupKind)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRESTMapper_RESTMappings_Call) Return(rESTMappings []*meta.RESTMapping, err error) *MockRESTMapper_RESTMappings_Call {
	_c.Call.Return(rESTMappings, err)
	return _c
}

func (_c *MockRESTMapper_RESTMappings_Call) RunAndReturn(run func(gk schema.GroupKind, versions ...string) ([]*meta.RESTMapping, error)) *MockRESTMapper_RESTMappings_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceFor provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) ResourceFor(input schema.GroupVersionResource) (schema.GroupVersionResource, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ResourceFor")
	}

	var r0 schema.GroupVersionResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) (schema.GroupVersionResource, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) schema.GroupVersionResource); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(schema.GroupVersionResource)
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_ResourceFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceFor'
type MockRESTMapper_ResourceFor_Call struct {
	*mock.Call
}

// ResourceFor is a helper method to define mock.On call
//   - input schema.GroupVersionResource
func (_e *MockRESTMapper_Expecter) ResourceFor(input interface{}) *MockRESTMapper_ResourceFor_Call {
	return &MockRESTMapper_ResourceFor_Call{Call: _e.mock.On("ResourceFor", input)}
}

func (_c *MockRESTMapper_ResourceFor_Call) Run(run func(input schema.GroupVersionResource)) *MockRESTMapper_ResourceFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRESTMapper_ResourceFor_Call) Return(groupVersionResource schema.GroupVersionResource, err error) *MockRESTMapper_ResourceFor_Call {
	_c.Call.Return(groupVersionResource, err)
	return _c
}

func (_c *MockRESTMapper_ResourceFor_Call) RunAndReturn(run func(input schema.GroupVersionResource) (schema.GroupVersionResource, error)) *MockRESTMapper_ResourceFor_Call {
	_c.Call.Return(run)
	return _c
}

// ResourceSingularizer provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) ResourceSingularizer(resource string) (string, error) {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for ResourceSingularizer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(resource)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(resource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_ResourceSingularizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourceSingularizer'
type MockRESTMapper_ResourceSingularizer_Call struct {
	*mock.Call
}

// ResourceSingularizer is a helper method to define mock.On call
//   - resource string
func (_e *MockRESTMapper_Expecter) ResourceSingularizer(resource interface{}) *MockRESTMapper_ResourceSingularizer_Call {
	return &MockRESTMapper_ResourceSingularizer_Call{Call: _e.mock.On("ResourceSingularizer", resource)}
}

func (_c *MockRESTMapper_ResourceSingularizer_Call) Run(run func(resource string)) *MockRESTMapper_ResourceSingularizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRESTMapper_ResourceSingularizer_Call) Return(singular string, err error) *MockRESTMapper_ResourceSingularizer_Call {
	_c.Call.Return(singular, err)
	return _c
}

func (_c *MockRESTMapper_ResourceSingularizer_Call) RunAndReturn(run func(resource string) (string, error)) *MockRESTMapper_ResourceSingularizer_Call {
	_c.Call.Return(run)
	return _c
}

// ResourcesFor provides a mock function for the type MockRESTMapper
func (_mock *MockRESTMapper) ResourcesFor(input schema.GroupVersionResource) ([]schema.GroupVersionResource, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ResourcesFor")
	}

	var r0 []schema.GroupVersionResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) ([]schema.GroupVersionResource, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) []schema.GroupVersionResource); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schema.GroupVersionResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(schema.GroupVersionResource) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRESTMapper_ResourcesFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResourcesFor'
type MockRESTMapper_ResourcesFor_Call struct {
	*mock.Call
}

// ResourcesFor is a helper method to define mock.On call
//   - input schema.GroupVersionResource
func (_e *MockRESTMapper_Expecter) ResourcesFor(input interface{}) *MockRESTMapper_ResourcesFor_Call {
	return &MockRESTMapper_ResourcesFor_Call{Call: _e.mock.On("ResourcesFor", input)}
}

func (_c *MockRESTMapper_ResourcesFor_Call) Run(run func(input schema.GroupVersionResource)) *MockRESTMapper_ResourcesFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRESTMapper_ResourcesFor_Call) Return(groupVersionResources []schema.GroupVersionResource, err error) *MockRESTMapper_ResourcesFor_Call {
	_c.Call.Return(groupVersionResources, err)
	return _c
}

func (_c *MockRESTMapper_ResourcesFor_Call) RunAndReturn(run func(input schema.GroupVersionResource) ([]schema.GroupVersionResource, error)) *MockRESTMapper_ResourcesFor_Call {
	_c.Call.Return(run)
	return _c
}
