apiVersion: core.platform-mesh.io/v1alpha1
kind: SearchIndex
metadata:
  labels:
    app.kubernetes.io/name: search-operator
    app.kubernetes.io/managed-by: kustomize
  name: searchindex-sample
spec:
  # TODO(user): Add fields here
