// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenRefresher creates a new instance of MockTokenRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRefresher {
	mock := &MockTokenRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRefresher is an autogenerated mock type for the TokenRefresher type
type MockTokenRefresher struct {
	mock.Mock
}

type MockTokenRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRefresher) EXPECT() *MockTokenRefresher_Expecter {
	return &MockTokenRefresher_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function for the type MockTokenRefresher
func (_mock *MockTokenRefresher) RefreshToken(ctx context.Context, clientID string) (string, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRefresher_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockTokenRefresher_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockTokenRefresher_Expecter) RefreshToken(ctx interface{}, clientID interface{}) *MockTokenRefresher_RefreshToken_Call {
	return &MockTokenRefresher_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, clientID)}
}

func (_c *MockTokenRefresher_RefreshToken_Call) Run(run func(ctx context.Context, clientID string)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) Return(newToken string, err error) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(newToken, err)
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, clientID string) (string, error)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
