name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: platform-mesh/.github/.github/workflows/job-golang-lint.yml@main

  test:
    uses: platform-mesh/.github/.github/workflows/job-golang-test-source.yml@main
    secrets: inherit
    with:
      coverageThresholdFile: 0
      coverageThresholdPackage: 0
      coverageThresholdTotal: 0

  quality-gate:
    if: always()
    permissions: {}
    needs: [lint, test]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check results
        run: |
          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            echo "lint failed"
            exit 1
          fi
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            echo "test failed"
            exit 1
          fi
