---
apiVersion: v1
kind: Namespace
metadata:
  name: graphql-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphql-gateway
  namespace: graphql-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graphql-gateway-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: graphql-gateway
    namespace: graphql-gateway
---
apiVersion: gateway.platform-mesh.io/v1alpha1
kind: ClusterAccess
metadata:
  name: local
spec:
  host: https://127.0.0.1:55624
  auth:
    serviceAccountRef:
      name: graphql-gateway
      namespace: graphql-gateway
