/*
Copyright 2025.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package manager contains just the setup for the mcr manager and broker.
package manager

import (
	"fmt"

	"k8s.io/apimachinery/pkg/runtime/schema"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"

	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/cluster"

	mctrl "sigs.k8s.io/multicluster-runtime"
	"sigs.k8s.io/multicluster-runtime/pkg/multicluster"
	"sigs.k8s.io/multicluster-runtime/providers/multi"
	"sigs.k8s.io/multicluster-runtime/providers/single"

	brokerv1alpha1 "github.com/platform-mesh/resource-broker/api/broker/v1alpha1"
	"github.com/platform-mesh/resource-broker/pkg/broker"
)

func init() {
	utilruntime.Must(brokerv1alpha1.AddToScheme(scheme.Scheme))
	// +kubebuilder:scaffold:scheme
}

// Options are the options for setting up the manager.
type Options struct {
	MgrOptions mctrl.Options

	// Name is a workaround because SkipNameValidation does not seem to work
	Name string

	// Local is the config for the local cluster where the manager will
	// run.
	Local *rest.Config

	// Compute is a client for the compute cluster. The compute cluster
	// is where the actual resources required for platform operations
	// are created.
	ComputeConfig *rest.Config

	// Coordination is a client for the coordination cluster. The
	// coordination cluster is where the e.g. brokerv1alpha1.Migration
	// resources are stored.
	CoordinationConfig *rest.Config

	// Consumer and Provider are the multicluster providers for the
	// consumer and provider clusters, respectively.
	Consumer, Provider multicluster.Provider

	// GVKs are the GVKs to broker.
	GVKs []schema.GroupVersionKind
}

// Setup sets up the manager and the broker.
func Setup(opts Options) (mctrl.Manager, error) {
	// TODO: The clients generated by the clusters coming out of the
	// proivders from mcr use this scheme and the manager should use it
	// as well. Not convention but it is what is is.
	opts.MgrOptions.Scheme = scheme.Scheme

	providers := multi.New(multi.Options{})
	if err := providers.AddProvider(broker.ConsumerPrefix, opts.Consumer); err != nil {
		return nil, fmt.Errorf("unable to add consumer provider: %w", err)
	}
	if err := providers.AddProvider(broker.ProviderPrefix, opts.Provider); err != nil {
		return nil, fmt.Errorf("unable to add provider provider: %w", err)
	}

	coordinationCluster, err := cluster.New(
		opts.CoordinationConfig,
		func(o *cluster.Options) {
			o.Scheme = scheme.Scheme
		},
	)
	if err != nil {
		return nil, fmt.Errorf("unable to create coordination cluster: %w", err)
	}
	if err := providers.AddProvider(broker.CoordinationPrefix, single.New("coord", coordinationCluster)); err != nil {
		return nil, fmt.Errorf("unable to add coordination provider: %w", err)
	}

	computeClient, err := client.New(opts.ComputeConfig, client.Options{
		Scheme: scheme.Scheme,
	})
	if err != nil {
		return nil, fmt.Errorf("unable to create compute client: %w", err)
	}

	mgr, err := mctrl.NewManager(opts.Local, providers, opts.MgrOptions)
	if err != nil {
		return nil, fmt.Errorf("unable to start manager: %w", err)
	}

	if _, err := broker.NewBroker(
		opts.Name,
		mgr,
		coordinationCluster.GetClient(),
		computeClient,
		opts.GVKs...,
	); err != nil {
		return nil, fmt.Errorf("unable to set up broker with manager: %w", err)
	}

	return mgr, nil
}
