apiVersion: authorization.platform-mesh.io/v1alpha1
kind: APIExportPolicy
metadata:
  name: orchestrate-platform-mesh-io
  namespace: platform-mesh-system
spec:
  apiExportRef:
    name: orchestrate.platform-mesh.io
    clusterPath: root:providers:httpbin

  allowPathExpressions:
    # Allow binding only for specific account and its child accounts
    - :root:orgs:default:abc
    - :root:orgs:default:cde
    # Allow binding for all accounts in all organizations
    - :root:orgs:*
    # Allow binding for all accounts within demo organization
    - :root:orgs:demo:*