/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package subroutines

import (
	"context"
	"fmt"
	"time"

	"go.platform-mesh.io/apis/terminal/v1alpha1"
	"go.platform-mesh.io/golang-commons/logger"
	"go.platform-mesh.io/subroutines"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"

	kerrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	HTTPRouteSubroutineName      = "HTTPRouteSubroutine"
	HTTPRouteSubroutineFinalizer = "terminal.platform-mesh.io/httproute-finalizer"
	HTTPRouteRequeueAfter        = 5 * time.Second

	nameLabel         = "app.kubernetes.io/name"
	instanceLabel     = "app.kubernetes.io/instance"
	managedByLabel    = "app.kubernetes.io/managed-by"
	terminalNameLabel = "terminal.platform-mesh.io/terminal-name"

	nameLabelValue = "terminal"
	managedBy      = "terminal-controller-manager"
)

// HTTPRouteSubroutine manages terminal HTTPRoutes on the runtime cluster
type HTTPRouteSubroutine struct {
	runtimeClient client.Client
	namespace     string
	gatewayName   string
	gatewayNs     string
	hostnames     []string
}

func NewHTTPRouteSubroutine(runtimeClient client.Client, namespace, gatewayName, gatewayNs string, hostnames []string) *HTTPRouteSubroutine {
	// Default hostnames if not provided
	if len(hostnames) == 0 {
		hostnames = []string{"portal.localhost", "*.portal.localhost"}
	}

	return &HTTPRouteSubroutine{
		runtimeClient: runtimeClient,
		namespace:     namespace,
		gatewayName:   gatewayName,
		gatewayNs:     gatewayNs,
		hostnames:     hostnames,
	}
}

func (r *HTTPRouteSubroutine) GetName() string {
	return HTTPRouteSubroutineName
}

func (r *HTTPRouteSubroutine) Finalizers(_ client.Object) []string { // coverage-ignore
	return []string{HTTPRouteSubroutineFinalizer}
}

func (r *HTTPRouteSubroutine) Finalize(ctx context.Context, obj client.Object) (subroutines.Result, error) {
	instance := obj.(*v1alpha1.Terminal)
	log := logger.LoadLoggerFromContext(ctx)

	routeName := fmt.Sprintf("terminal-%s", instance.Name)
	route := &gatewayv1.HTTPRoute{}
	routeKey := client.ObjectKey{Namespace: r.namespace, Name: routeName}

	if err := r.runtimeClient.Get(ctx, routeKey, route); err != nil {
		if kerrors.IsNotFound(err) || meta.IsNoMatchError(err) {
			return subroutines.OK(), nil
		}
		return subroutines.OK(), err
	}

	if route.GetDeletionTimestamp() != nil {
		log.Debug().Str("routeName", route.Name).Msg("HTTPRoute is already being deleted, waiting")
		return subroutines.StopWithRequeue(HTTPRouteRequeueAfter, "HTTPRoute is already being deleted"), nil
	}

	log.Info().Str("routeName", route.Name).Msg("deleting terminal HTTPRoute")
	if err := r.runtimeClient.Delete(ctx, route); err != nil {
		if kerrors.IsNotFound(err) {
			return subroutines.OK(), nil
		}
		return subroutines.OK(), err
	}

	return subroutines.StopWithRequeue(HTTPRouteRequeueAfter, "terminal HTTPRoute deletion requested"), nil
}

func (r *HTTPRouteSubroutine) Process(ctx context.Context, obj client.Object) (subroutines.Result, error) {
	instance := obj.(*v1alpha1.Terminal)
	log := logger.LoadLoggerFromContext(ctx)

	// Wait for session ID to be generated by PodSubroutine
	if instance.Status.SessionID == "" {
		log.Debug().Msg("waiting for session ID to be generated")
		return subroutines.StopWithRequeue(HTTPRouteRequeueAfter, "waiting for session ID to be generated"), nil
	}

	routeName := fmt.Sprintf("terminal-%s", instance.Name)

	route := &gatewayv1.HTTPRoute{
		ObjectMeta: metav1.ObjectMeta{
			Name:      routeName,
			Namespace: r.namespace,
		},
	}

	result, err := controllerutil.CreateOrUpdate(ctx, r.runtimeClient, route, func() error {
		r.mutateHTTPRoute(route, instance)
		return nil
	})
	if err != nil {
		return subroutines.OK(), err
	}

	log.Debug().Str("routeName", routeName).Str("result", string(result)).Msg("HTTPRoute reconciled")
	return subroutines.OK(), nil
}

func (r *HTTPRouteSubroutine) mutateHTTPRoute(route *gatewayv1.HTTPRoute, terminal *v1alpha1.Terminal) {
	serviceName := fmt.Sprintf("terminal-%s", terminal.Name)
	// Use session ID for non-guessable path
	pathPrefix := fmt.Sprintf("/terminals/%s", terminal.Status.SessionID)
	gatewayNs := gatewayv1.Namespace(r.gatewayNs)
	servicePort := gatewayv1.PortNumber(TerminalServicePort)

	route.Labels = map[string]string{
		nameLabel:         nameLabelValue,
		instanceLabel:     terminal.Name,
		managedByLabel:    managedBy,
		terminalNameLabel: terminal.Name,
	}
	// URL rewrite to strip prefix - ttyd expects requests at root /
	replacePath := "/"

	route.Spec = gatewayv1.HTTPRouteSpec{
		CommonRouteSpec: gatewayv1.CommonRouteSpec{
			ParentRefs: []gatewayv1.ParentReference{
				{
					Name:      gatewayv1.ObjectName(r.gatewayName),
					Namespace: &gatewayNs,
				},
			},
		},
		Hostnames: r.buildHostnames(),
		Rules: []gatewayv1.HTTPRouteRule{
			{
				Matches: []gatewayv1.HTTPRouteMatch{
					{
						Path: &gatewayv1.HTTPPathMatch{
							Type:  ptrTo(gatewayv1.PathMatchPathPrefix),
							Value: &pathPrefix,
						},
					},
				},
				Filters: []gatewayv1.HTTPRouteFilter{
					{
						Type: gatewayv1.HTTPRouteFilterURLRewrite,
						URLRewrite: &gatewayv1.HTTPURLRewriteFilter{
							Path: &gatewayv1.HTTPPathModifier{
								Type:               gatewayv1.PrefixMatchHTTPPathModifier,
								ReplacePrefixMatch: &replacePath,
							},
						},
					},
				},
				BackendRefs: []gatewayv1.HTTPBackendRef{
					{
						BackendRef: gatewayv1.BackendRef{
							BackendObjectReference: gatewayv1.BackendObjectReference{
								Name: gatewayv1.ObjectName(serviceName),
								Port: &servicePort,
							},
						},
					},
				},
			},
		},
	}
}

func (r *HTTPRouteSubroutine) buildHostnames() []gatewayv1.Hostname {
	if len(r.hostnames) == 0 {
		return nil
	}
	result := make([]gatewayv1.Hostname, len(r.hostnames))
	for i, h := range r.hostnames {
		result[i] = gatewayv1.Hostname(h)
	}
	return result
}

func ptrTo[T any](v T) *T {
	return &v
}

var _ subroutines.Processor = (*HTTPRouteSubroutine)(nil)
var _ subroutines.Finalizer = (*HTTPRouteSubroutine)(nil)
