# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: pr-gate

# Auto-merge gate for pull requests and merge queue.

on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read # Needed for actions/checkout
  checks: read # Needed to read check-run results for the gate
  pull-requests: read # Needed to read PR metadata
  statuses: read # Needed to read commit statuses for the gate

concurrency:
  group: pr-gate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # With GH_REPO set the repository doesn't need to be cloned just to run the gh cli
      GH_REPO: ${{ github.repository }}
      SELF: ${{ github.workflow }}
      PR: ${{ github.event.pull_request.number }}
    steps:
      - name: pr-gate
        run: |
          set -euo pipefail

          sleep 30  # let workflows register their checks first

          pending_checks() {
            gh pr checks "$PR" \
              --json bucket,workflow \
              --jq '.[] | select(.workflow != env.SELF) | select(.bucket as $val | ["pass", "skipping", "fail"] | index($val) | not )'
          }

          are_checks_pending() {
            [[ "$(pending_checks | wc -l)" -gt 0 ]]
          }

          failed_checks() {
            gh pr checks "$PR" --json bucket,workflow --jq '.[] | select(.bucket == "fail")'
          }

          are_any_failed() {
            [[ "$(failed_checks | wc -l)" -gt 0 ]]
          }

          while true; do
            if are_any_failed; then
              echo Some jobs failed, reporting failure
              exit 1
            fi
            if are_checks_pending; then
              echo Some jobs are still running, sleeping
              sleep 1
              continue
            fi
            break
          done

          echo All jobs finished, checking for failures
          if are_any_failed; then
            echo Some jobs failed, reporting failure
            exit 1
          fi
          echo No jobs failed, success!
