{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-sharding-operator.fullname" . }}
  labels:
    {{- include "resource-sharding-operator.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        sharding.platform-mesh.io/aggregate-to-operator: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-sharding-operator.fullname" . }}-base
  labels:
    {{- include "resource-sharding-operator.labels" . | nindent 4 }}
    sharding.platform-mesh.io/aggregate-to-operator: "true"
rules:
  - apiGroups: ["sharding.platform-mesh.io"]
    resources: ["resourceshardings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["sharding.platform-mesh.io"]
    resources: ["resourceshardings/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["sharding.platform-mesh.io"]
    resources: ["resourceshardings/finalizers"]
    verbs: ["update"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource-sharding-operator.fullname" . }}
  labels:
    {{- include "resource-sharding-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource-sharding-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource-sharding-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
